-- Generated by tools/dump_schema.php — do not edit by hand.
-- Schema version: 3

-- ---------------------------------------------------------------
-- Migration 1
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lot_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mobile VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(64) NULL,
    password_hash VARCHAR(255) NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_wallets (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    balance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    frozen DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    total_stake DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    total_payout DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_wallet_ledger (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    entry_key VARCHAR(80) NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    direction VARCHAR(6) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    balance_before DECIMAL(18,2) NOT NULL,
    balance_after DECIMAL(18,2) NOT NULL,
    ref_type VARCHAR(32) NOT NULL,
    ref_id VARCHAR(64) NULL,
    remark VARCHAR(191) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_ledger_user ON lot_wallet_ledger (user_id, id);

CREATE INDEX idx_ledger_ref ON lot_wallet_ledger (ref_type, ref_id);

CREATE TABLE IF NOT EXISTS lot_games (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_code VARCHAR(32) NOT NULL UNIQUE,
    family VARCHAR(24) NOT NULL,
    family_code VARCHAR(3) NOT NULL,
    interval_key VARCHAR(8) NOT NULL,
    interval_code VARCHAR(2) NOT NULL,
    interval_seconds INT NOT NULL,
    lock_seconds INT NOT NULL DEFAULT 5,
    sort INT NOT NULL DEFAULT 0,
    state TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_issues (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_code VARCHAR(32) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    lock_time DATETIME NOT NULL,
    status VARCHAR(12) NOT NULL DEFAULT 'open',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_issue UNIQUE (game_code, issue_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_issue_game_end ON lot_issues (game_code, end_time);

CREATE TABLE IF NOT EXISTS lot_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_code VARCHAR(32) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    family VARCHAR(24) NOT NULL,
    result_json JSON NOT NULL,
    primary_number INT NULL,
    color VARCHAR(24) NULL,
    sum_value INT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'local',
    draw_hash VARCHAR(64) NULL,
    drawn_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_result UNIQUE (game_code, issue_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_result_game ON lot_results (game_code, id);

CREATE TABLE IF NOT EXISTS lot_bets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bet_no VARCHAR(40) NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    game_code VARCHAR(32) NOT NULL,
    family VARCHAR(24) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    bet_type VARCHAR(32) NOT NULL,
    bet_content VARCHAR(191) NOT NULL,
    unit_amount DECIMAL(18,2) NOT NULL,
    multiplier INT NOT NULL DEFAULT 1,
    units INT NOT NULL DEFAULT 1,
    stake DECIMAL(18,2) NOT NULL,
    odds DECIMAL(10,4) NOT NULL DEFAULT 0,
    potential_payout DECIMAL(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(12) NOT NULL DEFAULT 'pending',
    payout_gross DECIMAL(18,2) NOT NULL DEFAULT 0,
    payout_tax DECIMAL(18,2) NOT NULL DEFAULT 0,
    payout_net DECIMAL(18,2) NOT NULL DEFAULT 0,
    vip_experience DECIMAL(18,2) NOT NULL DEFAULT 0,
    vip_counted TINYINT NOT NULL DEFAULT 0,
    source VARCHAR(16) NOT NULL DEFAULT 'manual',
    request_group_key VARCHAR(64) NULL,
    request_key VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_bet_user ON lot_bets (user_id, id);

CREATE INDEX idx_bet_issue ON lot_bets (game_code, issue_number, status);

CREATE UNIQUE INDEX uq_bet_request ON lot_bets (user_id, request_group_key, request_key);

CREATE TABLE IF NOT EXISTS lot_idempotency (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idem_key VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(48) NOT NULL,
    response_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_settlements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_code VARCHAR(32) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    bets_total INT NOT NULL DEFAULT 0,
    bets_won INT NOT NULL DEFAULT 0,
    stake_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    payout_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    tax_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    settled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_settlement UNIQUE (game_code, issue_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Migration 2
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lot_result_overrides (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_code VARCHAR(32) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    override_value VARCHAR(64) NOT NULL,
    mode VARCHAR(12) NOT NULL DEFAULT 'oneshot',
    status VARCHAR(12) NOT NULL DEFAULT 'pending',
    created_by VARCHAR(64) NULL,
    note VARCHAR(191) NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_override UNIQUE (game_code, issue_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_override_pending ON lot_result_overrides (game_code, status);

CREATE TABLE IF NOT EXISTS lot_user_vip (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    experience DECIMAL(18,2) NOT NULL DEFAULT 0,
    level INT NOT NULL DEFAULT 0,
    backfilled_at DATETIME NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_vip_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    entry_key VARCHAR(80) NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    source VARCHAR(24) NOT NULL,
    ref_id VARCHAR(64) NULL,
    experience_added DECIMAL(18,2) NOT NULL DEFAULT 0,
    experience_after DECIMAL(18,2) NOT NULL DEFAULT 0,
    level_before INT NOT NULL DEFAULT 0,
    level_after INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_vip_log_user ON lot_vip_log (user_id, id);

CREATE TABLE IF NOT EXISTS lot_follow_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    plan_code VARCHAR(48) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(191) NULL,
    game_code VARCHAR(32) NOT NULL,
    bet_type VARCHAR(32) NOT NULL,
    strategy VARCHAR(24) NOT NULL DEFAULT 'fixed',
    bet_content VARCHAR(191) NOT NULL,
    min_amount DECIMAL(18,2) NOT NULL DEFAULT 1.00,
    sort INT NOT NULL DEFAULT 0,
    state TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lot_follow_subscriptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    plan_id BIGINT UNSIGNED NOT NULL,
    plan_code VARCHAR(48) NOT NULL,
    game_code VARCHAR(32) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    multiplier INT NOT NULL DEFAULT 1,
    total_rounds INT NOT NULL DEFAULT 0,
    completed_rounds INT NOT NULL DEFAULT 0,
    stop_loss DECIMAL(18,2) NOT NULL DEFAULT 0,
    net_profit DECIMAL(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(12) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stopped_at DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_follow_active ON lot_follow_subscriptions (status, game_code);

CREATE INDEX idx_follow_user ON lot_follow_subscriptions (user_id, status);

CREATE TABLE IF NOT EXISTS lot_follow_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    subscription_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    game_code VARCHAR(32) NOT NULL,
    issue_number VARCHAR(17) NOT NULL,
    bet_id BIGINT UNSIGNED NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'placed',
    message VARCHAR(191) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_follow_order UNIQUE (subscription_id, issue_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Migration 3
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lot_admin_audit (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    actor VARCHAR(64) NOT NULL,
    action VARCHAR(48) NOT NULL,
    target VARCHAR(64) NULL,
    detail TEXT NULL,
    ip VARCHAR(45) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_audit_created ON lot_admin_audit (id);

