<?php

declare(strict_types=1);

namespace Lottery\Database;

use Lottery\Support\Clock;
use Lottery\Support\Log;
use PDOException;
use Throwable;

/**
 * Versioned schema migrator.
 *
 * The bootstrap calls {@see migrate()} on the first request (and after every
 * deploy); pending versions are applied in order and recorded in
 * lot_migrations. Migrations are written once with portability placeholders so
 * the identical schema runs on MySQL 8+ (production) and SQLite (dev/tests).
 */
class Migrator
{
    private Connection $db;

    public function __construct(Connection $db)
    {
        $this->db = $db;
    }

    /** Highest known schema version. */
    public function latestVersion(): int
    {
        return max(array_keys($this->migrations()));
    }

    public function currentVersion(): int
    {
        $this->ensureMigrationsTable();
        return (int) ($this->db->fetchValue('SELECT COALESCE(MAX(version), 0) FROM ' . Tables::MIGRATIONS) ?? 0);
    }

    /**
     * Apply every pending migration.
     *
     * @return array<int,int> versions applied during this call
     */
    public function migrate(): array
    {
        $this->ensureMigrationsTable();
        $current = $this->currentVersion();
        $applied = [];

        foreach ($this->migrations() as $version => $statements) {
            if ($version <= $current) {
                continue;
            }
            foreach ($statements as $sql) {
                $this->exec($this->translate($sql));
            }
            $this->db->execute(
                'INSERT INTO ' . Tables::MIGRATIONS . ' (version, applied_at) VALUES (?, ?)',
                [$version, Clock::dateTime()]
            );
            $applied[] = $version;
            Log::info('schema migration applied', ['version' => $version]);
        }

        if ($applied !== []) {
            $this->seed();
        }

        return $applied;
    }

    /** Idempotent reference data (games + default follow plans). */
    public function seed(): void
    {
        (new Seeder($this->db))->run();
    }

    private function ensureMigrationsTable(): void
    {
        $this->exec($this->translate(
            'CREATE TABLE IF NOT EXISTS ' . Tables::MIGRATIONS . ' (
                version {INT} NOT NULL PRIMARY KEY,
                applied_at {DATETIME} NOT NULL
            ){ENGINE}'
        ));
    }

    private function exec(string $sql): void
    {
        try {
            $this->db->pdo()->exec($sql);
        } catch (PDOException $e) {
            // "duplicate index/column" is benign when re-running a migration
            // against a partially-migrated legacy database.
            $message = strtolower($e->getMessage());
            if (str_contains($message, 'duplicate') || str_contains($message, 'already exists')) {
                return;
            }
            throw $e;
        }
    }

    /**
     * Full DDL for one driver — used by tools/dump_schema.php to keep
     * schema.sql in sync with the migrations.
     */
    public function schemaSql(bool $mysql = true): string
    {
        $out = ["-- Generated by tools/dump_schema.php — do not edit by hand.",
                '-- Schema version: ' . $this->latestVersion(), ''];

        foreach ($this->migrations() as $version => $statements) {
            $out[] = "-- ---------------------------------------------------------------";
            $out[] = "-- Migration {$version}";
            $out[] = "-- ---------------------------------------------------------------";
            foreach ($statements as $sql) {
                $statement = (string) preg_replace('/\n\s+/', "\n    ", $this->translate($sql, $mysql));
                $out[] = rtrim($statement) . ';';
                $out[] = '';
            }
        }

        return implode(PHP_EOL, $out) . PHP_EOL;
    }

    /** Replace portability placeholders with driver-specific SQL. */
    private function translate(string $sql, ?bool $forceMysql = null): string
    {
        $mysql = $forceMysql ?? $this->db->isMysql();

        $map = $mysql ? [
            '{PK}'       => 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY',
            '{BIGINT}'   => 'BIGINT UNSIGNED',
            '{INT}'      => 'INT',
            '{TINYINT}'  => 'TINYINT',
            '{MONEY}'    => 'DECIMAL(18,2)',
            '{RATE}'     => 'DECIMAL(10,4)',
            // LONGTEXT rather than JSON: MariaDB and MySQL 5.6 do not have a
            // native JSON type, and nothing here queries inside the document.
            '{JSON}'     => 'LONGTEXT',
            '{TEXT}'     => 'TEXT',
            '{DATETIME}' => 'DATETIME',
            '{NOW}'      => 'CURRENT_TIMESTAMP',
            '{ENGINE}'   => ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        ] : [
            '{PK}'       => 'INTEGER PRIMARY KEY AUTOINCREMENT',
            '{BIGINT}'   => 'INTEGER',
            '{INT}'      => 'INTEGER',
            '{TINYINT}'  => 'INTEGER',
            '{MONEY}'    => 'NUMERIC(18,2)',
            '{RATE}'     => 'NUMERIC(10,4)',
            '{JSON}'     => 'TEXT',
            '{TEXT}'     => 'TEXT',
            '{DATETIME}' => 'DATETIME',
            '{NOW}'      => 'CURRENT_TIMESTAMP',
            '{ENGINE}'   => '',
        ];

        return strtr($sql, $map);
    }

    /**
     * @return array<int,array<int,string>>
     */
    private function migrations(): array
    {
        $m = [];

        /* ------------------------------------------------ v1: core platform */
        $m[1] = [
            'CREATE TABLE IF NOT EXISTS ' . Tables::USERS . ' (
                id {PK},
                mobile VARCHAR(20) NOT NULL UNIQUE,
                nickname VARCHAR(64) NULL,
                password_hash VARCHAR(255) NULL,
                status {TINYINT} NOT NULL DEFAULT 1,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                updated_at {DATETIME} NULL
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::WALLETS . ' (
                user_id {BIGINT} NOT NULL PRIMARY KEY,
                balance {MONEY} NOT NULL DEFAULT 0.00,
                frozen {MONEY} NOT NULL DEFAULT 0.00,
                total_stake {MONEY} NOT NULL DEFAULT 0.00,
                total_payout {MONEY} NOT NULL DEFAULT 0.00,
                version {BIGINT} NOT NULL DEFAULT 0,
                updated_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::LEDGER . ' (
                id {PK},
                entry_key VARCHAR(80) NOT NULL UNIQUE,
                user_id {BIGINT} NOT NULL,
                direction VARCHAR(6) NOT NULL,
                amount {MONEY} NOT NULL,
                balance_before {MONEY} NOT NULL,
                balance_after {MONEY} NOT NULL,
                ref_type VARCHAR(32) NOT NULL,
                ref_id VARCHAR(64) NULL,
                remark VARCHAR(191) NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',
            'CREATE INDEX idx_ledger_user ON ' . Tables::LEDGER . ' (user_id, id)',
            'CREATE INDEX idx_ledger_ref ON ' . Tables::LEDGER . ' (ref_type, ref_id)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::GAMES . ' (
                id {PK},
                game_code VARCHAR(32) NOT NULL UNIQUE,
                family VARCHAR(24) NOT NULL,
                family_code VARCHAR(3) NOT NULL,
                interval_key VARCHAR(8) NOT NULL,
                interval_code VARCHAR(2) NOT NULL,
                interval_seconds {INT} NOT NULL,
                lock_seconds {INT} NOT NULL DEFAULT 5,
                sort {INT} NOT NULL DEFAULT 0,
                state {TINYINT} NOT NULL DEFAULT 1,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::ISSUES . ' (
                id {PK},
                game_code VARCHAR(32) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                start_time {DATETIME} NOT NULL,
                end_time {DATETIME} NOT NULL,
                lock_time {DATETIME} NOT NULL,
                status VARCHAR(12) NOT NULL DEFAULT \'open\',
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                CONSTRAINT uq_issue UNIQUE (game_code, issue_number)
            ){ENGINE}',
            'CREATE INDEX idx_issue_game_end ON ' . Tables::ISSUES . ' (game_code, end_time)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::RESULTS . ' (
                id {PK},
                game_code VARCHAR(32) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                family VARCHAR(24) NOT NULL,
                result_json {JSON} NOT NULL,
                primary_number {INT} NULL,
                color VARCHAR(24) NULL,
                sum_value {INT} NULL,
                source VARCHAR(16) NOT NULL DEFAULT \'local\',
                draw_hash VARCHAR(64) NULL,
                drawn_at {DATETIME} NOT NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                CONSTRAINT uq_result UNIQUE (game_code, issue_number)
            ){ENGINE}',
            'CREATE INDEX idx_result_game ON ' . Tables::RESULTS . ' (game_code, id)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::BETS . ' (
                id {PK},
                bet_no VARCHAR(40) NOT NULL UNIQUE,
                user_id {BIGINT} NOT NULL,
                game_code VARCHAR(32) NOT NULL,
                family VARCHAR(24) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                bet_type VARCHAR(32) NOT NULL,
                bet_content VARCHAR(191) NOT NULL,
                unit_amount {MONEY} NOT NULL,
                multiplier {INT} NOT NULL DEFAULT 1,
                units {INT} NOT NULL DEFAULT 1,
                stake {MONEY} NOT NULL,
                odds {RATE} NOT NULL DEFAULT 0,
                potential_payout {MONEY} NOT NULL DEFAULT 0,
                status VARCHAR(12) NOT NULL DEFAULT \'pending\',
                payout_gross {MONEY} NOT NULL DEFAULT 0,
                payout_tax {MONEY} NOT NULL DEFAULT 0,
                payout_net {MONEY} NOT NULL DEFAULT 0,
                vip_experience {MONEY} NOT NULL DEFAULT 0,
                vip_counted {TINYINT} NOT NULL DEFAULT 0,
                source VARCHAR(16) NOT NULL DEFAULT \'manual\',
                request_group_key VARCHAR(64) NULL,
                request_key VARCHAR(64) NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                settled_at {DATETIME} NULL
            ){ENGINE}',
            'CREATE INDEX idx_bet_user ON ' . Tables::BETS . ' (user_id, id)',
            'CREATE INDEX idx_bet_issue ON ' . Tables::BETS . ' (game_code, issue_number, status)',
            'CREATE UNIQUE INDEX uq_bet_request ON ' . Tables::BETS . ' (user_id, request_group_key, request_key)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::IDEMPOTENCY . ' (
                id {PK},
                idem_key VARCHAR(64) NOT NULL UNIQUE,
                user_id {BIGINT} NOT NULL,
                action VARCHAR(48) NOT NULL,
                response_json {JSON} NOT NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::SETTLEMENTS . ' (
                id {PK},
                game_code VARCHAR(32) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                bets_total {INT} NOT NULL DEFAULT 0,
                bets_won {INT} NOT NULL DEFAULT 0,
                stake_total {MONEY} NOT NULL DEFAULT 0,
                payout_total {MONEY} NOT NULL DEFAULT 0,
                tax_total {MONEY} NOT NULL DEFAULT 0,
                settled_at {DATETIME} NOT NULL DEFAULT {NOW},
                CONSTRAINT uq_settlement UNIQUE (game_code, issue_number)
            ){ENGINE}',
        ];

        /* ------------------------------- v2: admin overrides, VIP, following */
        $m[2] = [
            'CREATE TABLE IF NOT EXISTS ' . Tables::OVERRIDES . ' (
                id {PK},
                game_code VARCHAR(32) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                override_value VARCHAR(64) NOT NULL,
                mode VARCHAR(12) NOT NULL DEFAULT \'oneshot\',
                status VARCHAR(12) NOT NULL DEFAULT \'pending\',
                created_by VARCHAR(64) NULL,
                note VARCHAR(191) NULL,
                used_at {DATETIME} NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                CONSTRAINT uq_override UNIQUE (game_code, issue_number)
            ){ENGINE}',
            'CREATE INDEX idx_override_pending ON ' . Tables::OVERRIDES . ' (game_code, status)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::VIP . ' (
                user_id {BIGINT} NOT NULL PRIMARY KEY,
                experience {MONEY} NOT NULL DEFAULT 0,
                level {INT} NOT NULL DEFAULT 0,
                backfilled_at {DATETIME} NULL,
                updated_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::VIP_LOG . ' (
                id {PK},
                entry_key VARCHAR(80) NOT NULL UNIQUE,
                user_id {BIGINT} NOT NULL,
                source VARCHAR(24) NOT NULL,
                ref_id VARCHAR(64) NULL,
                experience_added {MONEY} NOT NULL DEFAULT 0,
                experience_after {MONEY} NOT NULL DEFAULT 0,
                level_before {INT} NOT NULL DEFAULT 0,
                level_after {INT} NOT NULL DEFAULT 0,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',
            'CREATE INDEX idx_vip_log_user ON ' . Tables::VIP_LOG . ' (user_id, id)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::FOLLOW_PLANS . ' (
                id {PK},
                plan_code VARCHAR(48) NOT NULL UNIQUE,
                name VARCHAR(64) NOT NULL,
                description VARCHAR(191) NULL,
                game_code VARCHAR(32) NOT NULL,
                bet_type VARCHAR(32) NOT NULL,
                strategy VARCHAR(24) NOT NULL DEFAULT \'fixed\',
                bet_content VARCHAR(191) NOT NULL,
                min_amount {MONEY} NOT NULL DEFAULT 1.00,
                sort {INT} NOT NULL DEFAULT 0,
                state {TINYINT} NOT NULL DEFAULT 1,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',

            'CREATE TABLE IF NOT EXISTS ' . Tables::FOLLOW_SUBS . ' (
                id {PK},
                user_id {BIGINT} NOT NULL,
                plan_id {BIGINT} NOT NULL,
                plan_code VARCHAR(48) NOT NULL,
                game_code VARCHAR(32) NOT NULL,
                amount {MONEY} NOT NULL,
                multiplier {INT} NOT NULL DEFAULT 1,
                total_rounds {INT} NOT NULL DEFAULT 0,
                completed_rounds {INT} NOT NULL DEFAULT 0,
                stop_loss {MONEY} NOT NULL DEFAULT 0,
                net_profit {MONEY} NOT NULL DEFAULT 0,
                status VARCHAR(12) NOT NULL DEFAULT \'active\',
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                stopped_at {DATETIME} NULL
            ){ENGINE}',
            'CREATE INDEX idx_follow_active ON ' . Tables::FOLLOW_SUBS . ' (status, game_code)',
            'CREATE INDEX idx_follow_user ON ' . Tables::FOLLOW_SUBS . ' (user_id, status)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::FOLLOW_ORDERS . ' (
                id {PK},
                subscription_id {BIGINT} NOT NULL,
                user_id {BIGINT} NOT NULL,
                game_code VARCHAR(32) NOT NULL,
                issue_number VARCHAR(17) NOT NULL,
                bet_id {BIGINT} NULL,
                status VARCHAR(16) NOT NULL DEFAULT \'placed\',
                message VARCHAR(191) NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                CONSTRAINT uq_follow_order UNIQUE (subscription_id, issue_number)
            ){ENGINE}',
        ];

        /* ------------------------------------- v3: admin panel audit trail */
        $m[3] = [
            'CREATE TABLE IF NOT EXISTS ' . Tables::AUDIT . ' (
                id {PK},
                actor VARCHAR(64) NOT NULL,
                action VARCHAR(48) NOT NULL,
                target VARCHAR(64) NULL,
                detail {TEXT} NULL,
                ip VARCHAR(45) NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',
            'CREATE INDEX idx_audit_created ON ' . Tables::AUDIT . ' (id)',
        ];

        /* ------------------------- v4: result feed domain whitelist (SaaS) */
        $m[4] = [
            'CREATE TABLE IF NOT EXISTS ' . Tables::DOMAINS . ' (
                id {PK},
                domain VARCHAR(191) NOT NULL UNIQUE,
                label VARCHAR(64) NULL,
                api_key VARCHAR(64) NOT NULL UNIQUE,
                status {TINYINT} NOT NULL DEFAULT 1,
                games {TEXT} NULL,
                rate_limit {INT} NOT NULL DEFAULT 0,
                requests_total {BIGINT} NOT NULL DEFAULT 0,
                blocked_total {BIGINT} NOT NULL DEFAULT 0,
                note VARCHAR(191) NULL,
                expires_at {DATETIME} NULL,
                last_seen_at {DATETIME} NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW}
            ){ENGINE}',
            'CREATE INDEX idx_domain_status ON ' . Tables::DOMAINS . ' (status)',

            'CREATE TABLE IF NOT EXISTS ' . Tables::DOMAIN_USAGE . ' (
                id {PK},
                domain_id {BIGINT} NOT NULL,
                day VARCHAR(10) NOT NULL,
                requests {BIGINT} NOT NULL DEFAULT 0,
                blocked {BIGINT} NOT NULL DEFAULT 0,
                CONSTRAINT uq_domain_day UNIQUE (domain_id, day)
            ){ENGINE}',
        ];

        /* ------------------- v5: partner sites (third-game integration) */
        $m[5] = [
            'CREATE TABLE IF NOT EXISTS ' . Tables::PARTNER_USERS . ' (
                id {PK},
                domain_id {BIGINT} NOT NULL,
                external_id VARCHAR(64) NOT NULL,
                user_id {BIGINT} NOT NULL,
                nickname VARCHAR(64) NULL,
                created_at {DATETIME} NOT NULL DEFAULT {NOW},
                last_login_at {DATETIME} NULL,
                CONSTRAINT uq_partner_user UNIQUE (domain_id, external_id)
            ){ENGINE}',
            'CREATE INDEX idx_partner_local ON ' . Tables::PARTNER_USERS . ' (user_id)',

            // Optional: a shared HS256 secret so we can accept the partner's
            // own player tokens directly.
            'ALTER TABLE ' . Tables::DOMAINS . ' ADD COLUMN player_secret VARCHAR(191) NULL',
        ];

        return $m;
    }

    /**
     * Best-effort bootstrap used by the HTTP kernel: never let a migration
     * failure take the whole API down when the schema is already current.
     */
    public function bootstrap(): void
    {
        try {
            if ($this->currentVersion() < $this->latestVersion()) {
                $this->migrate();
            }
        } catch (Throwable $e) {
            Log::exception($e, ['stage' => 'bootstrap-migrate']);
            throw $e;
        }
    }
}
